name: Work 1 Miguel
on:
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: echo "Impresion 1"
    - name: Print Something1
      run: echo "Impresion 2"
    - name: Print Something2
      run: echo "Impresion 3"